### ISSUE TITLE
Add mock data as JSON files

### ISSUE THREAD

**Issue by aprajshekhar** [gamedoora/gamedoora-ui#20]
**Describe the bug**
The mock data has to be available as JSON files in the public directory.

**To Reproduce**
The public directory does not have mock data as JSON files. 

**Expected behavior**
Each UI screen has hard coded data. 
The data has to come from mock data files and files would be in JSON format. 
The files need to reside in  directory named public  of the repo.

**Comment by Korra15** [comment]
#15 In this pull request I have added the json files for user-profile, user-studios and for the user-personalSpace.

**Comment by Korra15** [comment]
#15
